# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        self.MainWindow=MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        MainWindow.setStyleSheet("background-color: rgb(179, 193, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l_title = QtWidgets.QLabel(self.centralwidget)
        self.l_title.setGeometry(QtCore.QRect(250, 50, 311, 111))
        self.l_title.setStyleSheet("color: rgb(15, 27, 255);\n"
"font: 30pt \".SF NS Text\";")
        self.l_title.setObjectName("l_title")
        self.l_copyright = QtWidgets.QLabel(self.centralwidget)
        self.l_copyright.setGeometry(QtCore.QRect(260, 550, 261, 21))
        self.l_copyright.setStyleSheet("color: rgb(139, 139, 139);")
        self.l_copyright.setObjectName("l_copyright")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(120, 140, 591, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(180, 230, 151, 91))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(380, 220, 271, 111))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.txt_username = QtWidgets.QLineEdit(self.splitter_2)
        self.txt_username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 14pt \"Arial\";")
        self.txt_username.setObjectName("txt_username")
        self.txt_password = QtWidgets.QLineEdit(self.splitter_2)
        self.txt_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 14pt \"Arial\";")
        self.txt_password.setObjectName("txt_password")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 390, 271, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Submit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_Submit.setStyleSheet("color: rgb(250, 255, 255);\n"
"background-color: rgb(15, 47, 255);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 14pt \"Arial\";")
        self.btn_Submit.setObjectName("btn_Submit")
        self.verticalLayout.addWidget(self.btn_Submit)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l_title.setText(_translate("MainWindow", "Login Page"))
        self.l_copyright.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Author Shaishav</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">UserName</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
        self.txt_username.setPlaceholderText(_translate("MainWindow", "Enter UserName"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.btn_Submit.setText(_translate("MainWindow", "Submit"))

        self.btn_Submit.clicked.connect(self.btn_Submit_action)
    def btn_Submit_action(self):
        message=QMessageBox()
        passVAue=self.txt_password.text()
        usernameValue=self.txt_username.text()

        if passVAue=="admin" and usernameValue=="grantAdmin":
            print('Welcome to Youtube channel')
            message.setText("Hello World")
            message.exec()
            app.quit()
        else:
            message.setText("invalid username/password")
            message.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
